sudo: required
services: docker
language: bash

branches:
  only:
    - master

install:
  - docker build -t alpineros/ros-abuild:3.7-kinetic .
  - git clone --depth=1 -b indigo-devel https://github.com/ros/class_loader /tmp/class_loader

script:
  - docker run -it --rm -v /tmp/class_loader:/catkin:ro alpineros/ros-abuild:3.7-kinetic
