sudo: required
services: docker
language: bash

branches:
  only:
    - master

env:
  - ALPINE_VERSION=3.7 ROS_DISTRO=kinetic ROS_PYTHON_VERSION=2
  - ALPINE_VERSION=3.8 ROS_DISTRO=melodic ROS_PYTHON_VERSION=2
  - ALPINE_VERSION=3.11 ROS_DISTRO=noetic ROS_PYTHON_VERSION=3

install:
  - |
    docker build -t builder \
      --build-arg ALPINE_VERSION \
      --build-arg ROS_DISTRO \
      --build-arg ROS_PYTHON_VERSION .
  - git clone --depth=1 -b ${ROS_DISTRO}-devel https://github.com/ros/rospack /tmp/rospack

script:
  - |
    docker run -it --rm \
      -v /tmp/rospack:/src/rospack:ro \
      -v /tmp/apks:/packages \
      builder
  - test -f /tmp/apks/ros-${ROS_DISTRO}-rospack-dbg-*.apk
  - test -f /tmp/apks/ros-${ROS_DISTRO}-rospack-doc-*.apk
  - test -f $(find /tmp/apks -name "ros-${ROS_DISTRO}-rospack-*.apk" | grep -v "rospack-dbg" | grep -v "rospack-doc")
