name: build ros2
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - ALPINE_VERSION=3.17 ROS_DISTRO=humble ROS_PYTHON_VERSION=3
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build image
        run: |
          eval ${{ matrix.env }}
          image="ros-abuild:${ALPINE_VERSION}-${ROS_DISTRO}"

          docker build -t ${image} \
            --build-arg ALPINE_VERSION=${ALPINE_VERSION} \
            --build-arg ROS_DISTRO=${ROS_DISTRO} \
            --build-arg ROS_PYTHON_VERSION=${ROS_PYTHON_VERSION} .
      - name: Test ament_cmake
        run: |
          eval ${{ matrix.env }}
          image="ros-abuild:${ALPINE_VERSION}-${ROS_DISTRO}"

          package_name="ament_cmake_gtest"
          git clone --depth=1 -b ${ROS_DISTRO} https://github.com/ament/ament_lint /tmp/repo
          mkdir -p /tmp/apks
          chmod a+w /tmp/apks
          docker run --rm \
            -v /tmp/repo/${package_name}:/src/${package_name}:ro \
            -v /tmp/apks:/packages \
            ${image}

          apk_package_name=$(echo ${package_name} | sed -e "s|_|-|g" -e "s|^|ros-${ROS_DISTRO}-|g")
          ls -l /tmp/apks/*/*
          echo "Checking -dbg subpackage"
          ls -l /tmp/apks/*/* | grep -e "${apk_package_name}-dbg-[0-9\._git]\+-r0.apk"
          echo "Checking -doc subpackage"
          ls -l /tmp/apks/*/* | grep -e "${apk_package_name}-doc-[0-9\._git]\+-r0.apk"
          echo "Checking main package"
          ls -l /tmp/apks/*/* | grep -e "${apk_package_name}-[0-9\._git]\+-r0.apk"
      - name: Test ament_python
        run: |
          eval ${{ matrix.env }}
          image="ros-abuild:${ALPINE_VERSION}-${ROS_DISTRO}"

          package_name="ament_copyright"
          git clone --depth=1 -b ${ROS_DISTRO} https://github.com/ament/ament_lint /tmp/repo
          mkdir -p /tmp/apks
          chmod a+w /tmp/apks
          docker run --rm \
            -v /tmp/repo/${package_name}:/src/${package_name}:ro \
            -v /tmp/apks:/packages \
            ${image}

          apk_package_name=$(echo ${package_name} | sed -e "s|_|-|g" -e "s|^|ros-${ROS_DISTRO}-|g")
          ls -l /tmp/apks/*/*
          echo "Checking -dbg subpackage"
          ls -l /tmp/apks/*/* | grep -e "${apk_package_name}-dbg-[0-9\._git]\+-r0.apk"
          echo "Checking -doc subpackage"
          ls -l /tmp/apks/*/* | grep -e "${apk_package_name}-doc-[0-9\._git]\+-r0.apk"
          echo "Checking main package"
          ls -l /tmp/apks/*/* | grep -e "${apk_package_name}-[0-9\._git]\+-r0.apk"

      - name: Login to GitHub Container Registry
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: |
          eval ${{ matrix.env }}
          image="ros-abuild:${ALPINE_VERSION}-${ROS_DISTRO}"

          docker tag ${image} ghcr.io/${{ github.repository_owner }}/${image}
          docker push ghcr.io/${{ github.repository_owner }}/${image}
